version: '3'

services:
  dev_db:
    image: postgres:alpine
    container_name: wrench_dev
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wrench_dev
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5434:5432
    volumes:
      - wrench_dev:/var/lib/postgresql/data

  test_db:
    image: postgres:alpine
    container_name: wrench_test
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wrench_test
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5435:5432
    volumes:
      - wrench_test:/var/lib/postgresql/data

volumes:
  wrench_dev:
  wrench_test: